; PlatformIO Project Configuration File
;
;   Build options, upload options, library options and dependencies.

[env:uno]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

lib_deps =
    marcoschwartz/LiquidCrystal_I2C
    olkal/HX711_ADC
    bblanchon/ArduinoJson
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    adafruit/MAX6675 library
